export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';
export const GET_INPUT = 'GET_INPUT';
export const TOGGLE_SEARCH_RESULTS = 'TOGGLE_SEARCH_RESULTS';
export const GET_ADDRESS_PREDICTIONS = 'GET_ADDRESS_PREDICTIONS';
